# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "ehci_pci" "ahci" "xhci_pci" "usbhid" "usb_storage" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ "dm-snapshot" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "none";
      fsType = "tmpfs";
      options = [ "defaults" "mode=755" "size=16G" ];
    };

  fileSystems."/persist" =
    { device = "/dev/disk/by-uuid/46eb9bbb-d5b6-4c19-a2cc-84f606d663c7";
      fsType = "btrfs";
      options = [ "subvol=persist" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/46eb9bbb-d5b6-4c19-a2cc-84f606d663c7";
      fsType = "btrfs";
      options = [ "subvol=nix" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/799C-89B5";
      fsType = "vfat";
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/fb7bc4c9-a8e7-4f21-9d09-5c8ffa8d6265";
      fsType = "ext4";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/9bbde27c-83dc-4010-9ec4-4f297b222415"; }
      { device = "/dev/disk/by-uuid/cd2acac6-8c75-4381-b71c-905d72064b7a"; }
    ];

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
