# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  boot.initrd.availableKernelModules = [ "xhci_pci" "ehci_pci" "ahci" "usbhid" "sd_mod" "sr_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ "dm-snapshot" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/03954456-4edf-4ae1-9051-0c683cb904c3";
      fsType = "ext4";
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/1dad36a4-45df-48ce-9c7e-614e42d7a160";
      fsType = "ext4";
    };

  fileSystems."/home/louis" =
    { device = "/dev/disk/by-uuid/4d49a408-1391-4528-bebe-f6d58c2401f9";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/d5101aaf-1628-4639-ae86-d962e3446904";
      fsType = "ext4";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/af24e0c6-d7bc-44b3-93e1-90c92a5e143e"; }
    ];

  nix.maxJobs = lib.mkDefault 4;
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
